#!/bin/bash
PREFIX=${1-cluster}
DNS_SERVER=dns.${PREFIX}.spark
IP=$(ip -o -4 addr list eth0 | perl -n -e 'if (m{inet\s([\d\.]+)\/\d+\s}xms) { print $1 }')
export SPARK_MASTER_IP=$(hostname -f)
export SPARK_PUBLIC_DNS=$DNS_SERVER
env

curl  -H 'X-Auth-Token: mySecurityToken2' -X POST http://$DNS_SERVER/dnsmasq-rest-api/zones/spark/$IP/$(hostname -f)
curl  -H 'X-Auth-Token: mySecurityToken2' -X POST http://$DNS_SERVER/dnsmasq-rest-api/reload

# Start Spark Master
echo "starting Spark Master"
$SPARK_HOME/sbin/start-master.sh
#while [ 1 ];
#do
tail -f $SPARK_HOME/logs/*.out
#        sleep 10
#done
